sudo: required
language: php
php:
  - 7.1
  - 7.0
  - 5.6

env:
  - TRAVIS_NODE_VERSION="4"

notifications:
  email:
    on_success: always # default: change
    on_failure: never # default: always

matrix:
  allow_failures:
    - php: nightly

cache:
  yarn: true
  directories:
    - web/app/themes/gss/bower_components
    - web/app/themes/gss/node_modules

before_install:
  - cd web/app/themes/gss/

install:
  - nvm install $TRAVIS_NODE_VERSION
  - nvm use $TRAVIS_NODE_VERSION
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
  - yarn global add bower gulp jscs
  - yarn
  - composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require squizlabs/php_codesniffer

script:
  - npm run build
  - npm run jshint
  - npm run jscs
  - npm run phpcs
