sudo: false
language: php
php:
  - 7.1
  - 7.0
  - 5.6

env:
  - TRAVIS_NODE_VERSION="4"

matrix:
  allow_failures:
    - php: nightly

cache:
  yarn: true
  directories:
    - web/app/themes/gss/bower_components
    - web/app/themes/gss/node_modules

before_install:
  - cd web/app/themes/gss/

install:
  - nvm install $TRAVIS_NODE_VERSION
  - nvm use $TRAVIS_NODE_VERSION
  - yarn global bower gulp jscs
  - yarn
  - composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require squizlabs/php_codesniffer

script:
  - npm run build
  - npm run jshint
  - npm run jscs
  - phpcs --standard=ruleset.xml --extensions=php -n -s .
